apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 058835008914.dkr.ecr.ap-south-1.amazonaws.com/minichat_backend:latest
        ports:
        - containerPort: 3000
        env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: JWT_EXPIRES_IN
              value: "7d"
            - name: CORS_ORIGIN
              value: "*"