apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 058835008914.dkr.ecr.ap-south-1.amazonaws.com/minichat_frontend:latest
        ports:
        - containerPort: 80
