name: My_minichat_app

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  Configure_AWS_Credentials:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.4
        with:
          role-to-assume: arn:aws:iam::058835008914:role/github_actions_ecr_permission
          aws-region: ap-south-1

      - name: Check AWS identity
        run: aws sts get-caller-identity

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and Push Docker Images
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

          docker build -f ./frontend/Dockerfile -t my-minichat-app_frontend ./frontend

          docker tag my-minichat-app_frontend:latest public.ecr.aws/k5n5y8u0/minichat-frontend:latest

          docker push public.ecr.aws/k5n5y8u0/minichat-frontend:latest

          docker build -f ./backend/Dockerfile -t my-minichat-app_backend ./backend

          docker tag my-minichat-app_backend:latest public.ecr.aws/k5n5y8u0/minichat-backend:latest

          docker push public.ecr.aws/k5n5y8u0/minichat-backend:latest
  Deploy:
    needs: Configure_AWS_Credentials
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare SSH key
        run: |
          echo "${{ secrets.id_rsa }}" > id_rsa
          chmod 600 id_rsa

      - name: Copy deployment files
        run: |
          scp -o StrictHostKeyChecking=no -i id_rsa -r k8s ubuntu@65.0.123.46:/home/ubuntu/
      - name: Create Kubernetes secret
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          kubectl create secret generic postgres-secret \
            --from-literal=POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
            --from-literal=DATABASE_URL="$DATABASE_URL" \
            --from-literal=JWT_SECRET="$JWT_SECRET" \
            --dry-run=client \
            -o yaml > postgres-secret.yml

          scp -o StrictHostKeyChecking=no -i id_rsa postgres-secret.yml ubuntu@65.0.123.46:/home/ubuntu/k8s
      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i id_rsa ubuntu@65.0.123.46 << 'EOF'
          mv k8s/kind-config.yaml ..
          kind get clusters | grep -qx tws-kind-cluster || kind create cluster --config kind-config.yaml --name tws-kind-cluster
          kubectl apply -f k8s/
          EOF
      - name: Remove SSH key
        if: always()
        run: rm -f id_rsa
