name: My_minichat_app

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Configure_AWS_Credentials:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.4
        with:
          role-to-assume: arn:aws:iam::058835008914:role/github_actions_terraform
          aws-region: ap-south-1

      - name: Check AWS identity
        run: aws sts get-caller-identity

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Apply
        run: |
          cd terraform
          terraform init
          echo "Terraform initialzied"
          terraform plan
          terraform apply --auto-approve